/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forms;

/**
 *
 * @author Rodney
 */
public
        class frmPrincipal extends javax.swing.JFrame
{
    public frmPrincipal()
    {
        initComponents();
        classes.variaveis.casasDecimais = 4;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jbtnSoma = new javax.swing.JButton();
        jtxfNum1 = new javax.swing.JTextField();
        jtxfNum2 = new javax.swing.JTextField();
        jtxfRes = new javax.swing.JTextField();
        jbtnSub = new javax.swing.JButton();
        jbtnMult = new javax.swing.JButton();
        jbtnDiv = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiCasas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        jbtnSoma.setText("+");
        jbtnSoma.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbtnSomaActionPerformed(evt);
            }
        });

        jbtnSub.setText("-");
        jbtnSub.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbtnSubActionPerformed(evt);
            }
        });

        jbtnMult.setText("*");
        jbtnMult.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbtnMultActionPerformed(evt);
            }
        });

        jbtnDiv.setText("/");
        jbtnDiv.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbtnDivActionPerformed(evt);
            }
        });

        jMenu1.setText("Formatar");

        jmiCasas.setText("Casas decimais");
        jmiCasas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jmiCasasActionPerformed(evt);
            }
        });
        jMenu1.add(jmiCasas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnMult, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jbtnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxfNum1)
                    .addComponent(jtxfNum2)
                    .addComponent(jtxfRes))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jtxfNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxfNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSub)
                    .addComponent(jbtnSoma))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnMult)
                    .addComponent(jbtnDiv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxfRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSomaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbtnSomaActionPerformed
    {//GEN-HEADEREND:event_jbtnSomaActionPerformed
        classes.soma s = new classes.soma();
        jtxfRes.setText(s.somar(jtxfNum1.getText(), jtxfNum2.getText()));
    }//GEN-LAST:event_jbtnSomaActionPerformed

    private void jbtnSubActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbtnSubActionPerformed
    {//GEN-HEADEREND:event_jbtnSubActionPerformed
        classes.subtracao s = new classes.subtracao();
        jtxfRes.setText(s.subtrair(jtxfNum1.getText(), jtxfNum2.getText()));
    }//GEN-LAST:event_jbtnSubActionPerformed

    private void jbtnMultActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbtnMultActionPerformed
    {//GEN-HEADEREND:event_jbtnMultActionPerformed
        classes.multiplicacao s = new classes.multiplicacao();
        jtxfRes.setText(s.multiplicar(jtxfNum1.getText(), jtxfNum2.getText()));
    }//GEN-LAST:event_jbtnMultActionPerformed

    private void jbtnDivActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbtnDivActionPerformed
    {//GEN-HEADEREND:event_jbtnDivActionPerformed
        classes.divisao s = new classes.divisao();
        jtxfRes.setText(s.dividir(jtxfNum1.getText(), jtxfNum2.getText()));
    }//GEN-LAST:event_jbtnDivActionPerformed

    private void jmiCasasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmiCasasActionPerformed
    {//GEN-HEADEREND:event_jmiCasasActionPerformed
        forms.frmCasasDecimais frmcd = new forms.frmCasasDecimais(this, rootPaneCheckingEnabled);
        frmcd.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jmiCasasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static
            void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public
                    void run()
            {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbtnDiv;
    private javax.swing.JButton jbtnMult;
    private javax.swing.JButton jbtnSoma;
    private javax.swing.JButton jbtnSub;
    private javax.swing.JMenuItem jmiCasas;
    private javax.swing.JTextField jtxfNum1;
    private javax.swing.JTextField jtxfNum2;
    private javax.swing.JTextField jtxfRes;
    // End of variables declaration//GEN-END:variables
}
